### ISSUE TITLE
Installation fails on Ubuntu 20.04 with several "no such file or directory" errors

### ISSUE THREAD

**Issue by orasanen** [s0hv/DeepSpeakingAvatar#9]
./install.sh 
Submodule 'chatbot' (https://github.com/s0hv/chatbot) registered for path 'chatbot'
Submodule 'deep-speaking-avatar-text-to-audio' (https://github.com/vilukissa68/deep-speaking-avatar-text-to-audio) registered for path 'deep-speaking-avatar-text-to-audio'
Submodule 'face_detection' (https://github.com/viljamirom/face_detection) registered for path 'face_detection'
Submodule 'speech-to-text-translation' (https://github.com/Norskiii/speech-to-text-translation) registered for path 'speech-to-text-translation'
Setting up text2text
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/opt/DeepSpeakingAvatar/chatbot/venv/bin/python3 -m pip install --upgrade pip' command.
./install.sh: line 14: ./install-services.sh: No such file or directory
Text2text set up successfully
Setting up text2audio
./install.sh: line 23: ./src/setup_multivoice.sh: No such file or directory
Text2audio set up successfully
Setting up audio2text
./install.sh: line 31: ./setup.sh: No such file or directory
Audio2text set up successfully
Setting up face detection2
Collecting opencv-python==4.5.3.56
  Downloading opencv_python-4.5.3.56-cp39-cp39-manylinux2014_x86_64.whl (49.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 MB 4.4 MB/s eta 0:00:00
Collecting numpy>=1.19.3
  Downloading numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 4.6 MB/s eta 0:00:00
Installing collected packages: numpy, opencv-python
Successfully installed numpy-1.22.3 opencv-python-4.5.3.56
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/opt/DeepSpeakingAvatar/face_detection/venv/bin/python3 -m pip install --upgrade pip' command.

**Comment by orasanen** [comment]
Ah, need to recurse the submodules when cloning.

**Comment by s0hv** [comment]
Seems like the git command for cloning submodules was wrong. Fixed it in the latest commit and it should now automatically pull submodules when install.sh is run.
